IPRANGE   = "192.168.68."
IPSUFFIX  = "10"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-10"
  config.vm.box_version = "202107.08.0"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "graylog"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.hostname = "graylog"
  config.vm.network "private_network", ip: IPRANGE + IPSUFFIX
  config.vm.provision "file", source: "./scripts", destination: "~/scripts"
  config.vm.provision "shell", path: "./setup.sh"
end
